import {escapeHTML as esc} from './model.mjs';
import {atlasState,saveAtlas,sceneMapSource,tokenMapUV} from './atlas-state.mjs';
class SceneBrowser extends foundry.applications.api.ApplicationV2 {
  static DEFAULT_OPTIONS={id:'ra-scene-browser',classes:['ra-scene-browser'],window:{title:'Select Regional Scene',icon:'fa-solid fa-map',resizable:true},position:{width:560,height:540}};
  constructor(onChoose){super();this.onChoose=onChoose;}
  async _renderHTML(){return '<input type="search" name="search" placeholder="Search scenes" aria-label="Search Scenes"><div class="ra-scene-results"></div>';}
  _replaceHTML(html,content){content.innerHTML=html;}
  _onRender(c,o){super._onRender(c,o);this.element.querySelector('[name="search"]').addEventListener('input',e=>this.results(e.target.value));this.results('');}
  results(query){const scenes=game.scenes.contents.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())).slice(0,100);const node=this.element.querySelector('.ra-scene-results');node.innerHTML=scenes.map(s=>`<button type="button" data-uuid="${esc(s.uuid)}">${s.thumb?`<img src="${esc(s.thumb)}" alt="" loading="lazy">`:''}<span><strong>${esc(s.name)}</strong><small>${esc(s.folder?.name??'Scenes')}</small></span></button>`).join('')||'<p>No matching scenes.</p>';node.querySelectorAll('button').forEach(b=>b.addEventListener('click',async()=>{try{await this.onChoose(b.dataset.uuid);this.close();}catch(e){ui.notifications.warn(e.message);}}));}
}
export class RegionLinkDialog extends foundry.applications.api.ApplicationV2 {
  static DEFAULT_OPTIONS={id:'ra-region-link',tag:'form',classes:['standard-form','ra-region-link'],window:{title:'Link Regional Map',icon:'fa-solid fa-map-location-dot'},position:{width:560},form:{handler:RegionLinkDialog.submit,closeOnSubmit:false}};
  constructor(onLinked){super();this.onLinked=onLinked;this.scene=null;}
  async _renderHTML(){return `<p>Select the scene to use for this regional map.</p><div class="form-group"><label for="ra-region-uuid">Scene UUID</label><div class="form-fields"><input id="ra-region-uuid" name="uuid" value="${esc(atlasState().regional.sceneUuid)}" placeholder="Scene.…" required><button type="button" data-browse title="Browse Scenes" aria-label="Browse Scenes"><i class="fa-solid fa-folder-open"></i></button></div></div><p class="hint">Paste a Scene UUID, drop a scene here, or choose one from the scene browser.</p><div class="ra-link-preview"></div><div class="form-group"><label for="ra-region-token">Party Marker</label><select id="ra-region-token" name="token"><option value="">Place a Marker in the Atlas</option></select></div><p class="hint">Follow an existing token, or place a marker without moving scene tokens.</p><footer class="form-footer"><button type="submit">Link Map</button></footer>`;}
  _replaceHTML(html,content){content.innerHTML=html;}
  _onRender(c,o){super._onRender(c,o);this.element.querySelector('[data-browse]').addEventListener('click',()=>new SceneBrowser(uuid=>this.select(uuid)).render(true));this.element.querySelector('[name="uuid"]').addEventListener('change',e=>this.select(e.target.value).catch(e=>ui.notifications.warn(e.message)));this.element.addEventListener('dragover',e=>e.preventDefault());this.element.addEventListener('drop',e=>{e.preventDefault();try{const data=JSON.parse(e.dataTransfer.getData('text/plain'));if(data.uuid)this.select(data.uuid).catch(e=>ui.notifications.warn(e.message));}catch{}});if(atlasState().regional.sceneUuid)this.select(atlasState().regional.sceneUuid).catch(()=>{});}
  async select(uuid){this.element.querySelector('[name="uuid"]').value=uuid.trim();const scene=await fromUuid(uuid.trim());if(!scene||scene.documentName!=='Scene'||scene.pack)throw new Error('Choose a scene in this world.');if(!sceneMapSource(scene))throw new Error('That scene has no background map.');this.scene=scene;this.element.querySelector('.ra-link-preview').innerHTML=`<strong>${esc(scene.name)}</strong>`;const tokens=scene.tokens.contents.filter(t=>!t.hidden);const current=atlasState().regional.tokenUuid;const matches=tokens.filter(t=>/^(group|party|the party)$/i.test(t.name));const selected=tokens.find(t=>t.uuid===current)?.uuid??(matches.length===1?matches[0].uuid:'');this.element.querySelector('[name="token"]').innerHTML='<option value="">Place a Marker in the Atlas</option>'+tokens.map(t=>`<option value="${esc(t.uuid)}" ${selected===t.uuid?'selected':''}>${esc(t.name)}</option>`).join('');}
  static async submit(e,form,data){try{if(!game.user.isGM)throw new Error('Only a GM can link a regional map.');const uuid=String(data.object.uuid).trim();const scene=await fromUuid(uuid);if(!scene||scene.documentName!=='Scene'||scene.pack||!sceneMapSource(scene))throw new Error('Enter a valid world Scene UUID with a background map.');const token=data.object.token?await fromUuid(data.object.token):null;if(token&&token.parent?.uuid!==scene.uuid)throw new Error('The party marker must belong to the selected scene.');const marker=token?tokenMapUV(scene,token):null;await saveAtlas({regional:{sceneUuid:scene.uuid,tokenUuid:token?.uuid??'',marker,calibration:scene.uuid===atlasState().regional.sceneUuid?atlasState().regional.calibration??null:null,sourceId:scene.uuid===atlasState().regional.sceneUuid?atlasState().regional.sourceId??'':''}});await this.close();await this.onLinked?.();}catch(e){ui.notifications.error(e.message);}}
}
